import type { ComponentType } from "react";

import {
  mockAlbums,
  mockArtists,
  mockDojoModules,
  mockMetrics,
  mockPlayerTracks,
  mockRegistryItems,
  mockShowcaseEntries,
  mockVaultFragments,
} from "@/lib/mock-data/examples";
import type { SEIBadgeVariantProps } from "@seihouse/ui";

import {
  ActionStripPreview,
  AlbumCardPreview,
  AppShellPreview,
  AspectRatioPreview,
  AvatarPreview,
  ArtistCardPreview,
  BadgePreview,
  BottomNavigationPreview,
  ButtonPreview,
  CardPreview,
  ComboboxWorkbenchPreview,
  CommandPaletteWorkbenchPreview,
  ContainerPreview,
  DataTablePreview,
  DialogPreview,
  DojoModuleCardPreview,
  DrawerPreview,
  EmptyStatePreview,
  ErrorStatePreview,
  FieldPreview,
  FilterBarPreview,
  InputPreview,
  LoadingStatePreview,
  MediaRowPreview,
  MenuPreview,
  MetricCardWorkbenchPreview,
  MultiSelectComboboxPreview,
  NativeDrawerPreview,
  NavigationDrawerPreview,
  PanelPreview,
  PageHeaderPreview,
  PlayerShellWorkbenchPreview,
  PluginSlotWorkbenchPreview,
  PopoverPreview,
  ProgressBarPreview,
  RegistryPanelWorkbenchPreview,
  RegistrySealWorkbenchPreview,
  RadioGroupPreview,
  SafeAreaPreview,
  ScrollAreaPreview,
  ScrollLanePreview,
  SectionPreview,
  SelectPreview,
  ShowcaseBlockWorkbenchPreview,
  ShowcaseHeroWorkbenchPreview,
  SkeletonPreview,
  SliderPreview,
  SpinnerPreview,
  SplitPanePreview,
  StatusDotPreview,
  StickyFooterPreview,
  SuccessStatePreview,
  SwitchPreview,
  TabsPreview,
  TextareaPreview,
  ThumbnailPreview,
  TooltipPreview,
  ToastPreview,
  ToolbarPreview,
  VaultFragmentCardPreview,
  CheckboxPreview,
  ActionBarPreview,
} from "./previews";

/* ------------------------------------------------------------------ */
/* SEIHouse Component Workbench registry                                */
/* One entry per reviewable component. The workbench, gallery, and      */
/* home review queue all read from this file.                           */
/* ------------------------------------------------------------------ */

export type WorkbenchLayer =
  | "foundation"
  | "state"
  | "form"
  | "behavior"
  | "menu"
  | "music-particle"
  | "registry"
  | "layout"
  | "media";

export type ReviewStatus =
  | "not-designed"
  | "rough"
  | "reviewing"
  | "approved-foundation"
  | "experimental";

export interface MockDataOption {
  id: string;
  label: string;
}

export interface ReviewNotes {
  whatWorks: string;
  whatFeelsWrong: string;
  changeRequest: string;
  founderVerdict: string;
}

/** Props every workbench preview component receives. */
export interface ComponentPreviewProps {
  /** One of the entry's `variants` strings. */
  variant: string;
  /** Index into the entry's `mockDataOptions` (0 when none exist). */
  mockIndex: number;
}

export interface WorkbenchComponentEntry {
  name: string;
  slug: string;
  category: string;
  layer: WorkbenchLayer;
  status: ReviewStatus;
  /** Plain SEIHouse language — what this thing is for, in one breath. */
  description: string;
  variants: string[];
  defaultVariant: string;
  mockDataOptions?: MockDataOption[];
  preview: ComponentType<ComponentPreviewProps>;
  /** Ids from the context registry where this component appears. */
  contextExamples: string[];
  /** Placeholder review notes — real notes live in the founder's head + localStorage. */
  reviewNotes: ReviewNotes;
}

const emptyNotes: ReviewNotes = {
  whatWorks: "",
  whatFeelsWrong: "",
  changeRequest: "",
  founderVerdict: "",
};

export const layerMeta: Record<WorkbenchLayer, { label: string; order: number }> = {
  foundation: { label: "Foundation", order: 0 },
  state: { label: "States", order: 1 },
  form: { label: "Forms", order: 2 },
  behavior: { label: "Behavior", order: 3 },
  menu: { label: "Menus", order: 4 },
  layout: { label: "Layout", order: 5 },
  media: { label: "Media", order: 6 },
  "music-particle": { label: "Music Particles", order: 7 },
  registry: { label: "Registry", order: 8 },
};

export const statusMeta: Record<
  ReviewStatus,
  { label: string; badge: SEIBadgeVariantProps["variant"]; dot: string }
> = {
  "not-designed": { label: "Not designed", badge: "outline", dot: "bg-white/30" },
  rough: { label: "Rough", badge: "warning", dot: "bg-[var(--sh-color-warning)]" },
  reviewing: { label: "Reviewing", badge: "soft", dot: "bg-[var(--sh-color-sea)]" },
  "approved-foundation": {
    label: "Approved foundation",
    badge: "success",
    dot: "bg-[var(--sh-color-success)]",
  },
  experimental: {
    label: "Experimental",
    badge: "media-test",
    dot: "bg-[var(--sh-color-accent)]",
  },
};

export const componentRegistry: WorkbenchComponentEntry[] = [
  /* ---- Foundation ---- */
  {
    name: "Button",
    slug: "button",
    category: "Primitives",
    layer: "foundation",
    status: "approved-foundation",
    description:
      "The one native action button every SEIHouse surface uses — forms, players, registry.",
    variants: [
      "default",
      "soft",
      "outline",
      "ghost",
      "solid",
      "dark",
      "light",
      "glass-test",
      "media-test",
    ],
    defaultVariant: "solid",
    preview: ButtonPreview,
    contextExamples: ["registry-confirmation", "creator-dashboard"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Badge",
    slug: "badge",
    category: "Primitives",
    layer: "foundation",
    status: "reviewing",
    description: "Small status and label chips: release state, registry state, tags.",
    variants: [
      "default",
      "soft",
      "outline",
      "ghost",
      "solid",
      "dark",
      "light",
      "glass-test",
      "media-test",
      "success",
      "warning",
      "danger",
      "registry",
    ],
    defaultVariant: "default",
    preview: BadgePreview,
    contextExamples: ["sea-portal"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Card",
    slug: "card",
    category: "Primitives",
    layer: "foundation",
    status: "approved-foundation",
    description:
      "A semantic, composable card surface for media, identity, lore, metadata, actions, and product-driven accents.",
    variants: [
      "default",
      "soft",
      "outline",
      "ghost",
      "solid",
      "dark",
      "light",
      "glass-test",
      "media-test",
    ],
    defaultVariant: "default",
    preview: CardPreview,
    contextExamples: ["sea-portal"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Panel",
    slug: "panel",
    category: "Primitives",
    layer: "foundation",
    status: "approved-foundation",
    description: "Bigger surface than a card — players, registry panels, dashboards, with glass available as a built-in surface variant.",
    variants: [
      "default",
      "soft",
      "outline",
      "ghost",
      "solid",
      "dark",
      "light",
      "glass",
      "glass-glow",
      "glass-test",
      "media-test",
    ],
    defaultVariant: "default",
    preview: PanelPreview,
    contextExamples: ["creator-dashboard"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Section",
    slug: "section",
    category: "Primitives",
    layer: "foundation",
    status: "reviewing",
    description: "Page section header: eyebrow, title, short description, optional aside.",
    variants: ["sm", "md", "lg"],
    defaultVariant: "md",
    preview: SectionPreview,
    contextExamples: ["sea-portal"],
    reviewNotes: emptyNotes,
  },

  /* ---- States ---- */
  {
    name: "Skeleton",
    slug: "skeleton",
    category: "Loading",
    layer: "state",
    status: "reviewing",
    description: "Placeholder blocks for loading cards, rows, avatars, and text.",
    variants: ["pulse", "shimmer", "avatar", "card"],
    defaultVariant: "shimmer",
    preview: SkeletonPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Spinner",
    slug: "spinner",
    category: "Loading",
    layer: "state",
    status: "reviewing",
    description: "Compact loading indicator with an accessible status label.",
    variants: ["sm", "md", "lg"],
    defaultVariant: "md",
    preview: SpinnerPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Progress Bar",
    slug: "progress-bar",
    category: "Loading",
    layer: "state",
    status: "reviewing",
    description: "Determinate and indeterminate progress for uploads, sync, and readiness.",
    variants: ["sea", "success", "warning", "danger", "accent", "indeterminate"],
    defaultVariant: "sea",
    preview: ProgressBarPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Status Dot",
    slug: "status-dot",
    category: "Status",
    layer: "state",
    status: "reviewing",
    description: "Small decorative status dot plus readable status-line pairing.",
    variants: ["neutral", "sea", "success", "warning", "danger", "sea-pulse"],
    defaultVariant: "sea",
    preview: StatusDotPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Empty State",
    slug: "empty-state",
    category: "Status",
    layer: "state",
    status: "reviewing",
    description: "A calm empty surface with icon, copy, and optional action.",
    variants: ["sm", "md", "lg"],
    defaultVariant: "md",
    preview: EmptyStatePreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Loading State",
    slug: "loading-state",
    category: "Status",
    layer: "state",
    status: "reviewing",
    description: "Panel-sized loading state for routes and deferred panels.",
    variants: ["sm", "md", "lg"],
    defaultVariant: "md",
    preview: LoadingStatePreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Error State",
    slug: "error-state",
    category: "Status",
    layer: "state",
    status: "reviewing",
    description: "Recoverable error or warning state with accessible alert semantics.",
    variants: ["danger", "warning"],
    defaultVariant: "danger",
    preview: ErrorStatePreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Success State",
    slug: "success-state",
    category: "Status",
    layer: "state",
    status: "reviewing",
    description: "Confirmation state for completed setup, sync, or registry readiness.",
    variants: ["sm", "md", "lg"],
    defaultVariant: "md",
    preview: SuccessStatePreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Toast",
    slug: "toast",
    category: "Feedback",
    layer: "state",
    status: "reviewing",
    description: "Transient notifications with a reducer-backed queue and live-region semantics.",
    variants: ["default", "info", "success", "warning", "danger"],
    defaultVariant: "success",
    preview: ToastPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },

  /* ---- Forms ---- */
  {
    name: "Field",
    slug: "field",
    category: "Forms",
    layer: "form",
    status: "reviewing",
    description: "Label, helper, error, required, and disabled shell for native controls.",
    variants: ["comfortable", "compact", "required", "error", "disabled"],
    defaultVariant: "comfortable",
    preview: FieldPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Input",
    slug: "input",
    category: "Forms",
    layer: "form",
    status: "approved-foundation",
    description: "Styled native input with optional inside icons and invalid/disabled states.",
    variants: ["comfortable", "compact", "with-icons", "filled", "invalid", "disabled"],
    defaultVariant: "with-icons",
    preview: InputPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Textarea",
    slug: "textarea",
    category: "Forms",
    layer: "form",
    status: "approved-foundation",
    description: "Multi-line native text field using the shared form surface.",
    variants: ["comfortable", "compact", "filled", "invalid", "disabled"],
    defaultVariant: "comfortable",
    preview: TextareaPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Select",
    slug: "select",
    category: "Forms",
    layer: "form",
    status: "reviewing",
    description: "Native select with SEIHouse closed-state styling and chevron.",
    variants: ["comfortable", "compact", "invalid", "disabled"],
    defaultVariant: "comfortable",
    preview: SelectPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Switch",
    slug: "switch",
    category: "Forms",
    layer: "form",
    status: "reviewing",
    description: "Accessible React Aria toggle for binary settings.",
    variants: ["comfortable", "compact", "off", "disabled"],
    defaultVariant: "comfortable",
    preview: SwitchPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Checkbox",
    slug: "checkbox",
    category: "Forms",
    layer: "form",
    status: "reviewing",
    description: "Accessible checkbox with selected and indeterminate states.",
    variants: ["checked", "unchecked", "disabled"],
    defaultVariant: "checked",
    preview: CheckboxPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Radio Group",
    slug: "radio-group",
    category: "Forms",
    layer: "form",
    status: "reviewing",
    description: "React Aria radio group with roving focus and orientation support.",
    variants: ["vertical", "horizontal", "invalid"],
    defaultVariant: "vertical",
    preview: RadioGroupPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Slider",
    slug: "slider",
    category: "Forms",
    layer: "form",
    status: "reviewing",
    description: "Single-thumb React Aria slider for numeric controls.",
    variants: ["default", "low", "disabled"],
    defaultVariant: "default",
    preview: SliderPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },

  /* ---- Behavior ---- */
  {
    name: "Dialog",
    slug: "dialog",
    category: "Base UI",
    layer: "behavior",
    status: "reviewing",
    description: "Modal window for confirmations and detail views. Fully keyboard accessible.",
    variants: ["default", "soft", "dark", "light", "glass-test"],
    defaultVariant: "default",
    mockDataOptions: [
      { id: "confirm", label: "Confirm registration" },
      { id: "album", label: "Album details" },
    ],
    preview: DialogPreview,
    contextExamples: ["registry-confirmation"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Drawer",
    slug: "drawer",
    category: "Base UI",
    layer: "behavior",
    status: "reviewing",
    description: "Side or bottom panel for vault details, queues, and creator tools.",
    variants: ["right", "left", "bottom"],
    defaultVariant: "right",
    mockDataOptions: [
      { id: "vault", label: "Vault fragment detail" },
      { id: "queue", label: "Player queue" },
    ],
    preview: DrawerPreview,
    contextExamples: ["plugin-settings-drawer"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Native Drawer",
    slug: "native-drawer",
    category: "vaul",
    layer: "behavior",
    status: "reviewing",
    description: "Swipeable drawer with drag-to-dismiss and snap points, for mobile-feel panels.",
    variants: ["bottom", "right", "left"],
    defaultVariant: "bottom",
    mockDataOptions: [
      { id: "queue", label: "Player queue" },
      { id: "plugin", label: "Plugin settings" },
    ],
    preview: NativeDrawerPreview,
    contextExamples: ["plugin-settings-drawer"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Tabs",
    slug: "tabs",
    category: "Base UI",
    layer: "behavior",
    status: "reviewing",
    description: "Keyboard-navigable tabs for registry records, album worlds, and settings.",
    variants: ["default", "underline", "pill", "panel", "dark", "light"],
    defaultVariant: "underline",
    preview: TabsPreview,
    contextExamples: ["sea-portal"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Popover",
    slug: "popover",
    category: "Base UI",
    layer: "behavior",
    status: "reviewing",
    description: "Small floating panel anchored to a trigger — explanations and quick actions.",
    variants: ["default", "soft", "dark", "light"],
    defaultVariant: "default",
    preview: PopoverPreview,
    contextExamples: ["registry-confirmation"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Menu",
    slug: "menu",
    category: "Base UI",
    layer: "behavior",
    status: "reviewing",
    description: "Anchored dropdown menu for row actions, overflow actions, and settings.",
    variants: ["default", "soft", "dark", "light", "glass-test"],
    defaultVariant: "default",
    preview: MenuPreview,
    contextExamples: ["foundation-form-state"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Tooltip",
    slug: "tooltip",
    category: "Base UI",
    layer: "behavior",
    status: "reviewing",
    description: "Helper text on hover or keyboard focus, with a shared open delay.",
    variants: ["default"],
    defaultVariant: "default",
    preview: TooltipPreview,
    contextExamples: ["creator-dashboard"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Combobox",
    slug: "combobox",
    category: "React Aria",
    layer: "behavior",
    status: "reviewing",
    description: "Searchable single-select list for artists, tags, and metadata fields.",
    variants: ["default"],
    defaultVariant: "default",
    mockDataOptions: [
      { id: "artists", label: "Artist search" },
      { id: "vault-tags", label: "Vault tags" },
    ],
    preview: ComboboxWorkbenchPreview,
    contextExamples: ["vault-fragment-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Multi-Select Combobox",
    slug: "multi-select-combobox",
    category: "React Aria",
    layer: "behavior",
    status: "reviewing",
    description: "Tagging input with removable chips — vault tags, genres, registry labels.",
    variants: ["default"],
    defaultVariant: "default",
    mockDataOptions: [
      { id: "vault-tags", label: "Vault tags" },
      { id: "genres", label: "Album genres" },
      { id: "registry-labels", label: "Registry labels" },
      { id: "dojo-categories", label: "Dojo categories" },
    ],
    preview: MultiSelectComboboxPreview,
    contextExamples: ["vault-fragment-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Command Palette",
    slug: "command-palette",
    category: "Base UI + React Aria",
    layer: "behavior",
    status: "reviewing",
    description: "⌘K palette with fuzzy search, grouped commands, and recents. Nothing executes.",
    variants: ["default"],
    defaultVariant: "default",
    preview: CommandPaletteWorkbenchPreview,
    contextExamples: ["sea-portal"],
    reviewNotes: emptyNotes,
  },

  /* ---- Menus ---- */
  {
    name: "Bottom Navigation",
    slug: "bottom-navigation",
    category: "Menus",
    layer: "menu",
    status: "approved-foundation",
    description:
      "Mobile tab bar: icon + label destinations with active state, selection callback, and safe-area padding.",
    variants: ["four-items", "three-items", "five-items"],
    defaultVariant: "four-items",
    preview: BottomNavigationPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Navigation Drawer",
    slug: "navigation-drawer",
    category: "Menus",
    layer: "menu",
    status: "approved-foundation",
    description:
      "Mobile slide-in navigation: grouped icon + label sections, account header, settings actions, and safe-area padding.",
    variants: ["full", "sections-only", "right-side"],
    defaultVariant: "full",
    preview: NavigationDrawerPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },

  /* ---- Media ---- */
  {
    name: "Aspect Ratio",
    slug: "aspect-ratio",
    category: "Media",
    layer: "media",
    status: "reviewing",
    description: "Intrinsic ratio frame for artwork, video, thumbnails, and media placeholders.",
    variants: ["square", "video", "portrait"],
    defaultVariant: "square",
    preview: AspectRatioPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Thumbnail",
    slug: "thumbnail",
    category: "Media",
    layer: "media",
    status: "reviewing",
    description: "Artwork image frame with cover behavior and a gradient fallback.",
    variants: ["none", "sm", "md", "lg"],
    defaultVariant: "md",
    preview: ThumbnailPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Avatar",
    slug: "avatar",
    category: "Media",
    layer: "media",
    status: "reviewing",
    description: "Circular image or initials avatar for creators, collaborators, and entities.",
    variants: ["neutral", "sea", "accent"],
    defaultVariant: "sea",
    preview: AvatarPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Media Row",
    slug: "media-row",
    category: "Media",
    layer: "media",
    status: "reviewing",
    description: "Compact list row with leading media, title, subtitle, and trailing metadata.",
    variants: ["default", "interactive"],
    defaultVariant: "default",
    preview: MediaRowPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },

  /* ---- Music Particles ---- */
  {
    name: "Album Card",
    slug: "album-card",
    category: "Releases",
    layer: "music-particle",
    status: "reviewing",
    description: "A release world in card form: artwork, status, tags, and actions.",
    variants: ["default", "compact", "feature", "dark", "light", "media-test"],
    defaultVariant: "default",
    mockDataOptions: mockAlbums.map((album) => ({ id: album.id, label: album.title })),
    preview: AlbumCardPreview,
    contextExamples: ["album-world-hero"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Artist Card",
    slug: "artist-card",
    category: "Creators",
    layer: "music-particle",
    status: "reviewing",
    description: "Creator identity card: avatar, role, bio, tags, profile actions.",
    variants: ["default", "compact", "profile", "dark", "light"],
    defaultVariant: "default",
    mockDataOptions: mockArtists.map((artist) => ({ id: artist.id, label: artist.name })),
    preview: ArtistCardPreview,
    contextExamples: ["album-world-hero", "creator-dashboard"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Vault Fragment Card",
    slug: "vault-fragment-card",
    category: "Vault",
    layer: "music-particle",
    status: "reviewing",
    description: "One recovered idea from the vault: demos, voice notes, session notes.",
    variants: ["default", "recovery", "archive", "compact", "dark"],
    defaultVariant: "default",
    mockDataOptions: mockVaultFragments.map((fragment) => ({
      id: fragment.id,
      label: fragment.title,
    })),
    preview: VaultFragmentCardPreview,
    contextExamples: ["vault-fragment-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Dojo Module Card",
    slug: "dojo-module-card",
    category: "Dojo",
    layer: "music-particle",
    status: "reviewing",
    description: "A learning module: difficulty, category, progress, start action.",
    variants: ["default", "lesson", "template", "skill", "dark", "light"],
    defaultVariant: "lesson",
    mockDataOptions: mockDojoModules.map((module) => ({ id: module.id, label: module.title })),
    preview: DojoModuleCardPreview,
    contextExamples: ["sea-portal"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Player Shell",
    slug: "player-shell",
    category: "Player",
    layer: "music-particle",
    status: "reviewing",
    description: "The visual player: artwork, transport, queue, environment. No audio logic.",
    variants: ["expanded", "compact", "docked", "dark", "light"],
    defaultVariant: "expanded",
    mockDataOptions: mockPlayerTracks.map((track) => ({ id: track.id, label: track.title })),
    preview: PlayerShellWorkbenchPreview,
    contextExamples: ["sap-player-dock"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Plugin Slot",
    slug: "plugin-slot",
    category: "Plugins",
    layer: "music-particle",
    status: "reviewing",
    description: "Placeholder for future plugins: SAP, Vault Radio, creator tools.",
    variants: ["mocked", "planned", "experimental", "disabled"],
    defaultVariant: "mocked",
    mockDataOptions: [
      { id: "sap", label: "SAP" },
      { id: "vault-radio", label: "Vault Radio" },
      { id: "environment-engine", label: "Environment Engine" },
      { id: "registry-seal", label: "Registry Seal" },
      { id: "creator-tools", label: "Creator Tools" },
    ],
    preview: PluginSlotWorkbenchPreview,
    contextExamples: ["plugin-settings-drawer"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Metric Card",
    slug: "metric-card",
    category: "Dashboard",
    layer: "music-particle",
    status: "reviewing",
    description: "One dashboard number: plays, saves, registered works, vault items.",
    variants: ["default", "soft", "dark", "light", "outline"],
    defaultVariant: "default",
    mockDataOptions: mockMetrics.map((metric) => ({ id: metric.label, label: metric.label })),
    preview: MetricCardWorkbenchPreview,
    contextExamples: ["creator-dashboard"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Action Strip",
    slug: "action-strip",
    category: "Dashboard",
    layer: "music-particle",
    status: "reviewing",
    description: "A responsive row of actions: primary, secondary, and icon buttons.",
    variants: ["between", "start", "end"],
    defaultVariant: "between",
    preview: ActionStripPreview,
    contextExamples: ["creator-dashboard"],
    reviewNotes: emptyNotes,
  },

  /* ---- Registry ---- */
  {
    name: "Registry Seal",
    slug: "registry-seal",
    category: "Status",
    layer: "registry",
    status: "reviewing",
    description: "The verification chip: draft, registered, verified, archived, experimental.",
    variants: ["draft", "registered", "verified", "archived", "experimental"],
    defaultVariant: "verified",
    mockDataOptions: [
      { id: "with-id", label: "With registry ID" },
      { id: "label-only", label: "Label only" },
    ],
    preview: RegistrySealWorkbenchPreview,
    contextExamples: ["registry-confirmation"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Registry Panel",
    slug: "registry-panel",
    category: "Status",
    layer: "registry",
    status: "reviewing",
    description: "A full registry record: seal, mock ID, timestamp, and review actions.",
    variants: ["draft", "registered", "verified", "archived", "experimental"],
    defaultVariant: "verified",
    mockDataOptions: mockRegistryItems.map((item) => ({ id: item.id, label: item.title })),
    preview: RegistryPanelWorkbenchPreview,
    contextExamples: ["registry-confirmation"],
    reviewNotes: emptyNotes,
  },

  /* ---- Layout ---- */
  {
    name: "Container",
    slug: "container",
    category: "Layout",
    layer: "layout",
    status: "reviewing",
    description: "Responsive max-width and gutter wrapper for app content.",
    variants: ["sm", "md", "lg", "xl", "full"],
    defaultVariant: "lg",
    preview: ContainerPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "App Shell",
    slug: "app-shell",
    category: "Layout",
    layer: "layout",
    status: "reviewing",
    description: "Grid-based app scaffold with sticky header, optional sidebar, and main region.",
    variants: ["sidebar", "no-sidebar"],
    defaultVariant: "sidebar",
    preview: AppShellPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Page Header",
    slug: "page-header",
    category: "Layout",
    layer: "layout",
    status: "reviewing",
    description: "Page title block with eyebrow, description, actions, and optional breadcrumb.",
    variants: ["default", "actions", "breadcrumb", "plain"],
    defaultVariant: "actions",
    preview: PageHeaderPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Toolbar",
    slug: "toolbar",
    category: "Layout",
    layer: "layout",
    status: "reviewing",
    description: "Accessible horizontal toolbar with start/end slots and optional sticky behavior.",
    variants: ["default", "sticky"],
    defaultVariant: "default",
    preview: ToolbarPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Action Bar",
    slug: "action-bar",
    category: "Layout",
    layer: "layout",
    status: "reviewing",
    description: "Footer-style action row for primary and secondary commands.",
    variants: ["start", "between", "end"],
    defaultVariant: "end",
    preview: ActionBarPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Filter Bar",
    slug: "filter-bar",
    category: "Layout",
    layer: "layout",
    status: "reviewing",
    description: "Responsive row for filter chips, clear control, and result count.",
    variants: ["default", "single", "clearable"],
    defaultVariant: "clearable",
    preview: FilterBarPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Split Pane",
    slug: "split-pane",
    category: "Layout",
    layer: "layout",
    status: "reviewing",
    description: "Static two-region split layout. Draggable resizing remains deferred.",
    variants: ["sm", "md", "lg", "wide"],
    defaultVariant: "md",
    preview: SplitPanePreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Sticky Footer",
    slug: "sticky-footer",
    category: "Layout",
    layer: "layout",
    status: "reviewing",
    description: "Sticky bottom action region with safe-area padding.",
    variants: ["footer", "div"],
    defaultVariant: "footer",
    preview: StickyFooterPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Safe Area",
    slug: "safe-area",
    category: "Layout",
    layer: "layout",
    status: "reviewing",
    description: "Wrapper for applying device safe-area inset padding on selected edges.",
    variants: ["all", "top", "bottom"],
    defaultVariant: "all",
    preview: SafeAreaPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Scroll Area",
    slug: "scroll-area",
    category: "Scroll",
    layer: "layout",
    status: "reviewing",
    description: "Focusable vertical scroll region with top/bottom overflow shadows.",
    variants: ["default", "tall"],
    defaultVariant: "default",
    preview: ScrollAreaPreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Scroll Lane",
    slug: "scroll-lane",
    category: "Scroll",
    layer: "layout",
    status: "reviewing",
    description: "Focusable horizontal overflow lane with optional snap alignment.",
    variants: ["sm", "md", "lg", "snap"],
    defaultVariant: "md",
    preview: ScrollLanePreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Data Table",
    slug: "data-table",
    category: "Data",
    layer: "layout",
    status: "reviewing",
    description: "Semantic dense table with sticky sortable headers and checkbox row selection.",
    variants: ["comfortable", "compact"],
    defaultVariant: "compact",
    preview: DataTablePreview,
    contextExamples: ["layout-media-list"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Showcase Hero",
    slug: "showcase-hero",
    category: "Experience Blocks",
    layer: "layout",
    status: "reviewing",
    description: "Big page opener for album worlds and portal landings. Heavy by design.",
    variants: ["clean", "soft", "dark", "light", "media", "experimental"],
    defaultVariant: "media",
    mockDataOptions: mockShowcaseEntries.map((entry) => ({ id: entry.id, label: entry.eyebrow })),
    preview: ShowcaseHeroWorkbenchPreview,
    contextExamples: ["album-world-hero"],
    reviewNotes: emptyNotes,
  },
  {
    name: "Showcase Block",
    slug: "showcase-block",
    category: "Experience Blocks",
    layer: "layout",
    status: "reviewing",
    description: "Titled panel wrapper used to frame examples and grouped content.",
    variants: ["default", "soft", "outline", "glass-test", "media-test", "dark", "light"],
    defaultVariant: "default",
    preview: ShowcaseBlockWorkbenchPreview,
    contextExamples: ["sea-portal"],
    reviewNotes: emptyNotes,
  },
];

export function getComponentBySlug(slug: string): WorkbenchComponentEntry | undefined {
  return componentRegistry.find((entry) => entry.slug === slug);
}

export function getComponentsByLayer(layer: WorkbenchLayer): WorkbenchComponentEntry[] {
  return componentRegistry.filter((entry) => entry.layer === layer);
}

export function getComponentsByStatus(status: ReviewStatus): WorkbenchComponentEntry[] {
  return componentRegistry.filter((entry) => entry.status === status);
}

export const orderedLayers = (Object.keys(layerMeta) as WorkbenchLayer[]).sort(
  (a, b) => layerMeta[a].order - layerMeta[b].order,
);
